### ISSUE TITLE
Fix notification image render size in Knock in-app feed

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#8149]
## Description

Fixed in this PR: https://github.com/hicommonwealth/commonwealth/pull/8515

**Comment by timolegros** [comment]
Images are rendering in the in-app notifications feed but we should resize them appropriately since right now they appear full-size:

![Image](https://github.com/user-attachments/assets/82c5a8be-513f-4523-a275-da3792341b67)

**Comment by burtonator** [comment]
This should be easy to fix. Just use a photo of a smaller dog. Maybe a Chihuahua.

I think we'd we'd have to fix this with a CSS rule of something like 

```css

.knock_container img {
   max-width: 200px;
   max-height: 200px;
}

```
