### ISSUE TITLE
Update `user.starredCommunities` from `/status` response to include specific community data

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#8753]
### Description

Context: https://github.com/hicommonwealth/commonwealth/issues/4976

Update `user.starredCommunities` from `/status` response to include specific community data

### Engineering Requirements

Each community entry in `user.starredCommunities` from `/status` response should include this data
```yaml
community_id: string
redirect: string
icon_url: string
name: string
```
